WITH MaxSizePerYear AS (
    SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
),
YearlyDeviations AS (
    SELECT e.ID,
           EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR,
           ABS(m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV
    FROM ECOLI_DATA e
    JOIN MaxSizePerYear m ON EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = m.YEAR
)
SELECT yd.YEAR,
       yd.YEAR_DEV,
       yd.ID
FROM YearlyDeviations yd
ORDER BY yd.YEAR ASC, yd.YEAR_DEV ASC;
